---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Set facts for tasks playbooks from alert info
      set_fact:
        org: "{{ org }}" 
        cred: "{{ cred_name }}"
        usr: "{{ user_name }}"
        pwd: "{{ password }}"
        key: "{{ key }}"
        pph: "{{ passphrase }}"
      ignore_errors: true
      no_log: true

    - name: File test
      shell: >-
        echo '{{ cred }}' > /tmp/cred.pem;
        echo '{{ key }}' > /tmp/cred.key;
      ignore_errors: true

    - name: create credential on tower
      tower_credential:
          kind: ssh 
          state: present
          organization: "{{ org }}" 
          name: "{{ cred }}"
          username: "{{ usr }}"
          password: "{{ pwd }}"
          ssh_key_data: "{{ key }}"
          ssh_key_unlock: "{{ pph }}"
          tower_host: localhost
          validate_certs: false
      ignore_errors: true

    - name: File test
      shell: >-
        cat /tmp/cred.pem;
        cat /tmp/cred.key;
      ignore_errors: true

    - name: Ansible delete multiple file example
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /tmp/cred.pem
        - /tmp/cred.key

    - name: File test
      shell: >-
        ls -ltr /tmp/;
      ignore_errors: true